### ISSUE TITLE
Is wifi strength available in the API?

### ISSUE THREAD

**Issue by mikesalz** [binarydev/ha-generac#26]
@binarydev So far this fork has been rock solid.  Thank you again for your time and work on this!

Question - The Mobile Link app includes the wifi strength.  Do you know if this is available in the API?  And if so, would it be difficult to add to HA?  

![image](https://github.com/binarydev/ha-generac/assets/46855061/fe6f51a3-4712-4389-80b1-b2aba059cec3)

**Comment by tgarrison3** [comment]
It doesn't appear to be in the /v2/apparatus/details api, but it is in the /v2/apparatus/list oddly enough.

**Comment by binarydev** [comment]
Glad it's been so solid :) the original code did have mentions of it and some commented out references, but I haven't tried to expose it. Let me take a look and see if I can get it added back in.

**Comment by binarydev** [comment]
Just published v0.2.1 which adds a new sensor to expose the wifi signal strength. It's presented in the API as a % string, so I just passed that through to the new sensor entity. The existing code from the original repo was trying to expose it as dbm (true signal strength whereas % is signal quality), but that can be done via a helper instead if you really wanted to. 

The new version should show up in your HACS interface as soon as it checks if an update is available (if you're using HACS that is, otherwise just copy-paste the latest code into your custom_components directory). You can also force it to recognize that an update is avilable by going to http://<your-ha-url>/hacs/repository/733708339 -> 3 dots on top right -> Update information. Then go to http://<your-ha-url>/hacs/entry to see the update available for install. After install you'll see the new sensor for the device listed: 
<img width="318" alt="Screenshot 2024-01-13 at 1 40 28 AM" src="https://github.com/binarydev/ha-generac/assets/979630/23ad1934-cf6b-46bb-a0f0-e6900ad4fc2d">

For anyone curious of how to convert % (quality) to strength (dbm): https://stackoverflow.com/questions/15797920/how-to-convert-wifi-signal-strength-from-quality-percent-to-rssi-dbm

**Comment by mikesalz** [comment]
This is great!  Thank you @binarydev!
